name: CI

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build & push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: fisolnasiet/java-as-myproject
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ fisolNasiet }}
          password: ${{ FiSoL2003! }}

