name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t fisolnasiet/java-as-myproject .
      - name: Publish image to docker hub
        run: docker push fisolnasiet/java-as-myproject:latest

  deploy:
    needs: build
    runs-on: [ aws-ec2 ]
    steps:
      - name: Pull Image from docker hub
        run: docker pull fisolnasiet/java-as-myproject:today
      - name: Delete old container
        run: docker rm -f java-as-myproject-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name java-as-myproject-container fisolnasiet/java-as-myproject